### ISSUE TITLE
Error creating new internal subscription

### ISSUE THREAD

**Issue by pietropau** [GridProtectionAlliance/openHistorian#10] opened 2016-07-05 17:38 UTC
Error when create a new "internal subscription " and click save on "manage device configuration".
Openhistorian version 2.0.347.0
![error_create_new_subscription](https://cloud.githubusercontent.com/assets/18598157/16593881/d6b76c34-42e7-11e6-84c6-ad7e32f6f72f.PNG)

Thanks,
Pietro

**Comment by ritchiecarroll** [comment] 2016-07-05 18:38
What type of database are you using so we can try to replicate your issue?

**Comment by pietropau** [comment] 2016-07-05 18:46
mysql 5.7 and OS windows server 2008.

**Comment by StephenCWills** [comment] 2016-07-05 19:36
I wasn't able to replicate the issue. Can you provide some more details? Does this happen every time you save, or did it just happen the first time?

**Comment by pietropau** [comment] 2016-07-06 06:31
it just happen when you save for the first time.

**Comment by StephenCWills** [comment] 2016-07-07 13:07
I tried several times with a couple different data sets, but I could not replicate this issue. Because it is difficult to replicate and because it only happens the first time you save the device, I am going to label this as wontfix and close the issue. If you can provide some more detailed information or a sample data set for reproducing the issue, I will try looking into it again.

**Closed by StephenCWills** 2016-07-07 13:07 UTC
Labels: bug, wontfix
